//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegralGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backstage_CommoditiesInformation
    {
        public int id { get; set; }
        public int Cid { get; set; }
        public int stock { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> Postage { get; set; }
        public string Ctitle { get; set; }
        public string explain { get; set; }
        public string exchangeInstructions { get; set; }
    }
}
