//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegralGO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntegralDataEntities : DbContext
    {
        public IntegralDataEntities()
            : base("name=IntegralDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Backstage_RotationChart> Backstage_RotationChart { get; set; }
        public virtual DbSet<Backstage_User> Backstage_User { get; set; }
        public virtual DbSet<Backstage_Commoditie> Backstage_Commoditie { get; set; }
        public virtual DbSet<Backstage_CommoditiesInformation> Backstage_CommoditiesInformation { get; set; }
    }
}
